name: acer-sway-os
description: Lightweight Sway desktop for Acer Aspire 722
base-image: ghcr.io/ublue-os/sway-atomic-main
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    install:
      # Broadcom WiFi driver
      - akmod-wl
      - broadcom-wl
      # Essential terminal and file manager
      - foot
      - nautilus
      # Browser
      - firefox
      # Sway utilities (most are pre-included, these are extras)
      - swaylock
      - swayidle
      - swaybg
      - wl-clipboard
      # System utilities
      - htop
      - curl
      - wget
      - nano
      # Audio/media (optional)
      - pavucontrol
      - alsa-utils
