name: acer-sway-os
description: Lightweight Sway desktop for Acer Aspire 722 (AMD C-60)
base-image: ghcr.io/ublue-os/sway-atomic-main
image-version: 43

modules:
  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
    install:
      - akmod-wl
      - broadcom-wl
      - foot
      - nautilus
      - firefox
      - swaylock
      - swayidle
      - swaybg
      - wl-clipboard
      - htop
      - curl
      - wget
      - nano
      - pavucontrol
      - alsa-utils
