name: acer-minimal-os
description: Minimal UBlue base for Acer C-50 (2GB RAM)
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
    install:
      - xorg-x11-server-Xvfb
      - openbox
      - xterm
      - htop
      - curl
      - wget
      - nano
      - tmux
