# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: acer-minimal-os
description: Minimal UBlue for Acer C-50 netbook (2GB RAM)
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  # Install packages via rpm-ostree
  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
    install:
      # Display server and window manager
      - xorg-x11-server-Xorg
      - xorg-x11-xinit
      - openbox
      - obconf
      - tint2
      - feh
      - lightdm
      - lightdm-gtk
      # Terminal and basic apps
      - xterm
      - pcmanfm
      - mousepad
      # System utilities
      - htop
      - curl
      - wget
      - nano
      - tmux
      # Networking
      - NetworkManager
      - nm-connection-editor
      - network-manager-applet
      # Hardware support
      - mesa-dri-drivers
      - xorg-x11-drv-amdgpu
      - linux-firmware

  # Copy system configuration files
  - type: files
    files:
      - source: system
        destination: /

  # Create default user and configure system
  - type: script
    scripts:
      - setup-user.sh
      - configure-desktop.sh

  # Enable systemd services
  - type: systemd
    system:
      enabled:
        - lightdm.service
        - NetworkManager.service

  # Sign the image
  - type: signing
